### ISSUE TITLE
Doesn't work storing data to string and Tempfile

### ISSUE THREAD

**Issue by xronos-i-am** [srijan/ruby-dmtx#6]
```
[2] pry(main)> Rdmtx.new.encode("Hello you !!", 5, 5).to_blob
Magick::ImageMagickError: no decode delegate for this image format `' @ error/blob.c/ImageToBlob/1553
from (pry):2:in `to_blob'
```

```
[3] pry(main)> Rdmtx.new.encode("Hello you !!", 5, 5).write(Tempfile.new)
Magick::ImageMagickError: no encode delegate for this image format `' @ error/constitute.c/WriteImage/1176
from (pry):3:in `write'
```

**Comment by srijan** [comment]
@xronos-i-am 

You need to tell imagemagick which format to use when exporting to blob or to file.

When writing to a filename like `output.png`, imagemagick guesses the format from the file extension.

So, you can make it work in one of these ways:

1. Explicitly tell imagemagick the format:
```
i = Rdmtx.new.encode("Hello you !!", 5, 5)
i.format = 'png'
i.to_blob
```

2. Ensure that tempfile is created with right extension:
```
Rdmtx.new.encode("Hello you !!", 5, 5).write(Tempfile.new(["", ".png"]).path)
```

You can substitute `png` for the format of your choice.

**Comment by xronos-i-am** [comment]
It works, thank you!
