### ISSUE TITLE
Bumping rmagick dependency

### ISSUE THREAD

**Issue by silasb** [srijan/ruby-dmtx#8]
Can we bump the `rmagick` dependency to `~> 4`?

**Comment by srijan** [comment]
It's already `~> 4`. Do you mean `~> 5`?

(Originally published at: https://srijan.ch/notes/2023-11-15-002)

**Comment by silasb** [comment]
Sorry, yes, to `~> 5`.

**Comment by srijan** [comment]
Released 0.5.0 with `rmagick ~> 5`
